BulkyWeb/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.DataAccess.Data;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly BulkyBookWebDbContext dbContext;

        public CompanyController(IUnitOfWork unitOfWork,BulkyBookWebDbContext dbContext)
        {
            this.unitOfWork = unitOfWork;
            this.dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var companyList = unitOfWork.Company.GetAll().ToList();

            return View(companyList);
        }

        public IActionResult UpsertCompany(int? id)
        {
            if (id == null)
            {
                //Create Company
                var company = new Company();

                return View(company);
            }
            else
            {
                //Update Company
                var company = unitOfWork.Company.Get(c => c.CompanyId == id);
                return View(company);
            }
        }

        [HttpPost]
        public IActionResult UpsertCompany(Company company)
        {
            if (ModelState.IsValid)
            {
                if(company.CompanyId == 0 || company.CompanyId == null)
                {
                    //Create Company
                    unitOfWork.Company.Add(company);
                    unitOfWork.Save();
                    TempData["success"] = "Company Successfully Created";

                    return RedirectToAction("Index");
                }
                else
                {
                    //Update Company
                    unitOfWork.Company.Update(company);
                    unitOfWork.Save();
                    TempData["success"] = "Company Successfully Updated";

                    return RedirectToAction("Index");
                }
            }
            else
            {
                return View(company);
            }
        }

        public IActionResult RemoveCompany(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var company = unitOfWork.Company.Get(c =>c.CompanyId == id);

            return View(company);
        }

        [HttpPost]
        public IActionResult RemoveCompany(Company company)
        {
            unitOfWork.Company.Remove(company);
            unitOfWork.Save();

            return RedirectToAction("Index");
        }
    }
}

BulkyWeb/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess.Data;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly BulkyBookWebDbContext dbContext;

        public ProductController(IUnitOfWork unitOfWork,IWebHostEnvironment webHostEnvironment, BulkyBookWebDbContext dbContext)
        {
            this.unitOfWork = unitOfWork;
            this.webHostEnvironment = webHostEnvironment;
            this.dbContext = dbContext;
        }

        public IActionResult Index(string? searchString)
        {
            if (!string.IsNullOrEmpty(searchString))
            {
                var productsearchtList = unitOfWork.Product.GetAll(includeProperties: "Category")
                    .Where(x => x.Title.Contains(searchString,StringComparison.OrdinalIgnoreCase) || 
                    x.Category.Name.Contains(searchString, StringComparison.OrdinalIgnoreCase)).ToList();

                return View(productsearchtList);
            }
            else
            {
                var productList = unitOfWork.Product.GetAll(includeProperties:"Category").ToList();

                return View(productList);
            }
        }

        public IActionResult UpsertProduct(int? id)
        {
            IEnumerable<SelectListItem> categoryList = unitOfWork.Category
            .GetAll().Select(x => new SelectListItem
            {
               Text = x.Name,
               Value=x.CategoryId.ToString(),
            });

            ProductVM productVm = new ProductVM()
            {
                Product = new Product(),
                CategoryList = categoryList,
            };

            if(id == null || id == 0)
            {
                //Create
                return View(productVm);
            }
            else
            {
                //Update
                productVm.Product = unitOfWork.Product.Get(p => p.ProductId == id);
                 
                if(productVm.Product == null)
                {
                    return NotFound();
                }
                return View(productVm);
            }
            
        }

        [HttpPost]
        public IActionResult UpsertProduct(ProductVM productVM, IFormFile? file)
        {
             if (ModelState.IsValid)
             {
                string wwwRootPath = webHostEnvironment.WebRootPath;

                if(file != null)
                {
                    string productPath = Path.Combine(wwwRootPath, @"images\products");
                    string fileName = Guid.NewGuid().ToString()+Path.GetExtension(file.FileName);

                    if (!string.IsNullOrEmpty(productVM.Product.ImageUrl))
                    {
                        //Delete the old image
                        var oldImagePath = Path.Combine(wwwRootPath,productVM.Product.ImageUrl.TrimStart('\\'));

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    productVM.Product.ImageUrl = @"images\products\" + fileName;
                }

                if(productVM.Product.ProductId != 0 || productVM.Product.ProductId != null)
                {
                    unitOfWork.Product.Update(productVM.Product);
                }
                else
                {
                    unitOfWork.Product.Add(productVM.Product);
                }
                unitOfWork.Save();
                TempData["success"] = "Product Successfully Created";
                return RedirectToAction("Index");
             }
             else
             {
                productVM.CategoryList = unitOfWork.Category.GetAll().Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.CategoryId.ToString(),
                });
                return View(productVM);
             }
        }

       /* public IActionResult UpdateProduct(int? id)
        {
            if (id == null || id <= 0)
            {
                return BadRequest("The id you are provided is irrelevent");
            }

            Product? product = unitOfWork.Product.Get(x => x.ProductId == id);
            //Product? product1= dbContext.Categories.Find(id);
            //Product? product2= dbContext.Categories.Where(x => x.ProductId == id).FirstOrDefault();

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [HttpPost]
        public IActionResult UpdateProduct(Product product)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Product.Update(product);
                unitOfWork.Save();
                TempData["success"] = "Product Updated Successfully";
                return RedirectToAction("Index");
            }
            return View();
        }*/

        public IActionResult RemoveProduct(int? id)
        {
            if (id == null || id <= 0)
            {
                return BadRequest("The Id you are provided is not Valid");
            }

            var product = unitOfWork.Product.Get(x => x.ProductId == id,includeProperties:"Category");
            IEnumerable<SelectListItem> categorieList = unitOfWork.Category.GetAll().Select(c => new SelectListItem()
            {
                Text= c.Name,
                Value = c.CategoryId.ToString(),
            });

            var productVm = new ProductVM()
            {
                CategoryList = categorieList,
                Product = product
            };

            if (productVm == null)
            {
                return NotFound();
            }
            return View(productVm);
        }

        [HttpPost]
        public IActionResult RemoveProduct(ProductVM productVM)
        {
            var productDomain = unitOfWork.Product.Get(x => x.ProductId == productVM.Product.ProductId);

            if (productVM.Product == null)
            {
                return NotFound();
            }

            string oldFilePath = Path.Combine(webHostEnvironment.WebRootPath, productVM.Product.ImageUrl.TrimStart('\\'));

            if (System.IO.File.Exists(oldFilePath))
            {
                System.IO.File.Delete(oldFilePath);
            }

            unitOfWork.Product.Remove(productDomain);
            unitOfWork.Save();
            TempData["success"] = "Product Deleted Successfully";

            return RedirectToAction("Index");
        }

        #region API Calls

        public IActionResult GetAll() 
        { 
            var productList = unitOfWork.Product.GetAll(includeProperties:"Category");

            return Json(new { data  = productList });
        }

        #endregion

    }
}

BulkyWeb/Areas/Customer/Controllers/CartController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkyBookWeb.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public CartController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        private double GetPriceBasedOnQuantity(ShoppingCart shoppingCart)
        {
            if (shoppingCart.ProductCount <= 50)
            {
                return shoppingCart.Product.Price;
            }
            else if (shoppingCart.ProductCount >= 51 && shoppingCart.ProductCount <= 100)
            {
                return shoppingCart.Product.Price50;
            }
            else
            {
                return shoppingCart.Product.Price100;
            }
        }

        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            var shoppingCartList = unitOfWork.ShoppingCart.GetAll(x => x.UserId == userId, includeProperties: "Product");

            ShoppingCartVM shoppingCartVM = new ShoppingCartVM()
            {
                ShoppingCartList = shoppingCartList,
            };

            foreach (var cart in shoppingCartVM.ShoppingCartList)
            {
                cart.Product.Price = GetPriceBasedOnQuantity(cart);
                shoppingCartVM.OrderTotal += (cart.Product.Price * cart.ProductCount);
            }

            return View(shoppingCartVM);
        }

        public IActionResult Increment(int cartId)
        {
            var cardDb = unitOfWork.ShoppingCart.Get(x => x.ShoppingCartId == cartId);
            cardDb.ProductCount += 1;

            unitOfWork.ShoppingCart.Update(cardDb);
            unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Decrement(int cartId)
        {
            var cardDb = unitOfWork.ShoppingCart.Get(x => x.ShoppingCartId == cartId);

            if (cardDb.ProductCount <= 1)
            {
                unitOfWork.ShoppingCart.Remove(cardDb);
                unitOfWork.Save();
            }
            else
            {
                cardDb.ProductCount -= 1;

                unitOfWork.ShoppingCart.Update(cardDb);
                unitOfWork.Save();
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveProduct(int cartId)
        {
            var cardDb = unitOfWork.ShoppingCart.Get(x => x.ShoppingCartId == cartId);

            unitOfWork.ShoppingCart.Remove(cardDb);
            unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Summary()
        {
            return View();
        }
    }
}

BulkyWeb/Controllers/CategoryController.cs
using BulkyBook.DataAccess.Data;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace BulkyBookWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly BulkyBookWebDbContext dbContext;

        public CategoryController(IUnitOfWork unitOfWork,BulkyBookWebDbContext dbContext)
        {
            this.unitOfWork = unitOfWork;
            this.dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var categoryList= unitOfWork.Category.GetAll().ToList();
            return View(categoryList);
        }

        public IActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateCategory(Category category)
        {
           if(ModelState.IsValid)
            {
                unitOfWork.Category.Add(category);
                unitOfWork.Save();
                TempData["success"] = "Category Successfully Created";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult UpdateCategory(int? id)
        {
            if(id == null || id <= 0)
            {
                return BadRequest("The id you are provided is irrelevent");
            }

            Category? category= unitOfWork.Category.Get(x => x.CategoryId == id);
            //Category? category1= dbContext.Categories.Find(id);
            //Category? category2= dbContext.Categories.Where(x => x.CategoryId == id).FirstOrDefault();

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        public IActionResult UpdateCategory(Category category)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Category.Update(category);
                unitOfWork.Save();
                TempData["success"] = "Category Updated Successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult RemoveCategory(int? id)
        {
            if(id==null || id <= 0)
            {
                return BadRequest("The Id you are provided is not Valid");
            }

            var category = unitOfWork.Category.Get(x => x.CategoryId==id);

            if(category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        public IActionResult RemoveCategory(Category category)
        {
            var categoryDomain = unitOfWork.Category.Get(x => x.CategoryId == category.CategoryId);

            if(category == null)
            {
                return NotFound();
            }
            unitOfWork.Category.Remove(categoryDomain);
            unitOfWork.Save();
            TempData["success"] = "Category Deleted Successfully";

            return RedirectToAction("Index");
        }
    }
}

BulkyWeb/Views/Shared/_Layout.cshtml
@using BulkyBook.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] BulkyBookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.1.3/css/dataTables.dataTables.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-center" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-cart"></i> &nbsp;(0)
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_Notifications" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary  text-muted ">
        <div class="container text-white fs-3 text-center">
            Made with ❤️ by Sai Mahesh 😊
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.1.3/js/dataTables.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/fmlpbdt5ot9qoi67l8wb6hoftu4vl9x7zrjga0gew87g7r3p/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyWeb/Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@if(TempData["error"] != null)
{ 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["success"]')
    </script>
}